
    spring:
      datasource:
        url: jdbc:mysql://localhost:3306/adm_escola?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 123456

      #    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
#    username: ${mysql.username}
#    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect



