spring:
  datasource:
    url: jdbc:postgresql://${postgres.url}:${postgres.port}/${postgres.schema}
    username: ${postgres.username}
    password: ${postgres.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
